#!/bin/bash
# -*- mode: julia -*-
#=
JULIA="${JULIA:-julia}"
JULIA_CMD="${JULIA_CMD:-${JULIA} --color=yes --startup-file=no}"
exec ${JULIA_CMD} "${BASH_SOURCE[0]}" "$@"
=#

# Usage:
#   ci/build-subproject MAIN SUB
#
# Install a project at directory MAIN into a (sub)project at directory
# SUB.  Packages installed in SUB are then built and precompiled.

main, sub = ARGS

using Pkg

Pkg.activate(sub)

@info "Installing $main to $sub..."
@time Pkg.develop(PackageSpec(path=main))
@info "Installing... DONE"

@info "Building..."
@time if VERSION >= v"1.1.0-rc1"
    Pkg.build(verbose=true)
else
    Pkg.build()
end
@info "Building... DONE"

@info "Precompiling..."
@time Pkg.API.precompile()
@info "Precompiling... DONE"
