#!/bin/bash
# -*- mode: julia -*-
#=
JULIA="${JULIA:-julia}"
JULIA_CMD="${JULIA_CMD:-${JULIA} --color=yes --startup-file=no}"
project="$1"
shift
exec ${JULIA_CMD} --project="$project" "$@" "${BASH_SOURCE[0]}"
=#

# Usage:
#   ci/install-to DIRECTORY
#
# Install a project at current working directory a (sub)project at
# DIRECTORY.  Packages installed in DIRECTORY are then built and
# precompiled.

using Pkg
Pkg.develop(PackageSpec(path=pwd()))

@info "Building..."
@time if VERSION >= v"1.1.0-rc1"
    Pkg.build(verbose=true)
else
    Pkg.build()
end
@info "Building... DONE"

@info "Precompiling..."
@time Pkg.API.precompile()
@info "Precompiling... DONE"
